name: AdvectionSolver
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12.5
  - clang-format>=18.1.8
  - matplotlib>=3.9.2
  - mdformat>=0.7.17
  - mypy>=1.11.2
  - pip>=24.2
  - ruff>=0.6.2
  - pip:
      - mdformat-ruff>=0.1.3